### ISSUE TITLE
Spoiler Text Does Not Render Properly on Mobile

### ISSUE THREAD

**Issue by technizor** [technizor/YuYuYu-for-reddit#4]
Spoiler Text appears as a bad hyperlink on Reddit Mobile and Bacon Reader.

Expected: Black boxing appears where the spoiler text is, just like on /r/anime.

Steps to Reproduce (Reddit Mobile):
1. Using the regular reddit website, navigate to /r/YuYuYu and find a post or comment with a spoiler.
2. Change the hostname from www.reddit.com to m.reddit.com.
3. Spoiler text now does not render properly.

Steps to Reproduce (BaconReader):
1. Using BaconReader, navigate to /r/YuYuYu, and find a post or comment with a spoiler.
2. Spoiler text does not render properly.

**Comment by eritbh** [comment]
Not sure how current this is, but it's worth noting that the only thing you can actually do for spoiler tags on mobile is make sure you're using the right format. The supported format is the `[Title](/s "Text")` style, which your Naut addon supports. Any other rendering issues on mobile devices are up to the app developers.

**Comment by technizor** [comment]
@geo1088 Yep. This is a pretty old one. Different mobile clients have different problems with the spoiler tag implementations. 

An example would be [Reddit Sync shortcutting the tag](https://github.com/laurencedawson/reddit-sync-development/issues/1192) whenever it encounters a ) character within the `[Warning](#s "Text Spoiler (Here) Unfortunately visible stuff.")` hovertext portion.
